# Generated by Django 2.1.7 on 2019-03-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presaveddata',
            name='relative_humidity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presaveddata',
            name='temperature',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
