# Generated by Django 2.1.7 on 2019-03-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20190317_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dataRecord',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 15, 6, 59, 60240)),
        ),
    ]
