# Generated by Django 2.1.7 on 2019-03-22 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20190318_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=200)),
                ('temperature', models.IntegerField()),
                ('relative_humidity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 9, 46, 26, 664172)),
        ),
    ]
