# Generated by Django 2.1.7 on 2019-03-23 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20190322_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 13, 55, 17, 560405)),
        ),
    ]
