# Generated by Django 2.1.7 on 2019-03-23 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20190323_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentparameters',
            name='light',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 11, 26, 389792)),
        ),
    ]
