# Generated by Django 2.1.7 on 2019-03-23 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20190323_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentparameters',
            name='light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 13, 53, 996389)),
        ),
    ]
